parameters:
  database_driver: pdo_mysql
  database_host: localhost
  database_port: null
  database_name: formbuilder
  database_user: formbuilder
  database_password: formbuilder!@#
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 4af9702b6aa8b28a698fb28806dca271
  database_path: null
