jms_security_extra:
    secure_all_services: false
    expressions: true

security:

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main_provider:
           id: shib_user_provider
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: 'ROLE_USER'}
#                    admin: { password: adminpass, roles: 'role_admin' }
#                    "compass@ubc.ca": { password: adminpass, roles: 'role_admin' }
        db:
            entity: { class: Meot\FormBundle\Entity\User, property: username }
    # security.firewalls are moved to config_ENV.yml
    access_control:
        #- { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/builder, roles: ROLE_USER, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
