questions:
    type:     rest
    resource: Meot\FormBundle\Controller\QuestionController

responses:
    type:     rest
    parent:   questions
    resource: Meot\FormBundle\Controller\ResponseController

forms:
    type:     rest
    resource: Meot\FormBundle\Controller\FormController

form_questions:
    type:     rest
    parent:   forms
    resource: Meot\FormBundle\Controller\FormQuestionController
