index:
    path: /
    defaults: { _controller: MeotFormBundle:Default:index }

questions:
    type:     rest
    resource: Meot\FormBundle\Controller\QuestionController

forms:
    type:     rest
    resource: Meot\FormBundle\Controller\FormController
