questions:
    type:     rest
    resource: Meot\FormBundle\Controller\QuestionController

responses:
    type:     rest
    parent:   questions
    resource: Meot\FormBundle\Controller\ResponseController
