web:
    resource: "@MeotFormBundle/Controller"
    type:     annotation

questions:
    type:     rest
    prefix:   api
    resource: Meot\FormBundle\Controller\QuestionController

forms:
    type:     rest
    prefix:   api
    resource: Meot\FormBundle\Controller\FormController
